# Generated by Django 4.2.4 on 2023-08-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_bibliotecario_consejeroescolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotecario',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bibliotecario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bibliotecario',
            name='numero_identificacion',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
